// Ported VERBATIM from app.js `MERCHANT_RULES` (line 1079). Same entries, order,
// patterns, categoryKeys, and confidence/requiresReview flags. Only the value
// source (IMPORT_CONFIDENCE) is imported from the shared types module.
import { IMPORT_CONFIDENCE } from "./types";
import type { ImportConfidence } from "./types";

export interface BuiltinMerchantRule {
  pattern: string;
  categoryKey: string;
  confidence: ImportConfidence;
  requiresReview?: boolean;
}

export const BUILTIN_MERCHANT_RULES: BuiltinMerchantRule[] = [
  ...[
    "COLES",
    "WOOLWORTHS",
    "ALDI",
    "COLONIAL FRUIT",
    "S & S PRODUCE",
    "PACIFIC ASIAN MARKET",
    "SQ *FOODNESS ASIAN",
    "NO.1 CITY MART",
    "KT MART",
    "XIN HUA",
    "SAO SANG GROCERIES",
    "FISH PIER",
    "TUNSTALL FRESH",
    "SQ *DONCASTER",
    "KFL CONVENIENCE",
    "LECROIS BLACKBURN",
    "FRANKS QUALITY FRUIT",
    "HARRIS FARM",
    "COSTCO",
    "IGA",
    "FOODWORKS",
    "SUPABARN",
    "SPUDSHED",
    "FOODLAND",
    "FRIENDLY GROCER",
    "DRAKES",
    "RITCHIES",
    "THOMAS DUX",
    "NATURALLY ORGANIC",
    "NIGHT OWL",
    "PENGUIN",
  ].map((pattern) => ({ pattern, categoryKey: "grocery", confidence: IMPORT_CONFIDENCE.HIGH })),
  ...[
    "KFC",
    "MCDONALD",
    "HUNGRY JACKS",
    "HJS",
    "CAFE",
    "RESTAURANT",
    "CATERING",
    "SUSHI",
    "KEBAB",
    "PHO THIN",
    "SINO KITCHEN",
    "WONGS GOURMET",
    "MOLLY TEA",
    "STARBUCKS",
    "DAN MURPHYS",
    "KMART",
    "TARGET",
    "BUNNINGS",
    "IKEA",
    "TEMU",
    "TAOBAO",
    "PETBARN",
    "DAISO",
    "THE REJECT SHOP",
    "1382_WESTFIELD",
    "CIRCUM WASH",
    "NEW ELEMENT INVESTMENT",
    "SUPER CHEAP",
    "HONG HOT BREAD",
    "MITCHAM BADMINTON",
    "MEZE TABLE",
    "ECCO FOOD GROUP",
    "CORNWELL'S MITRE 10",
    "CENTRE COM",
    "JB HI-FI",
    "HARVEY NORMAN",
    "THE GOOD GUYS",
    "MYER",
    "DAVID JONES",
    "BIG W",
    "SPOTLIGHT",
    "BEST & LESS",
    "JAYCAR",
    "OFFICEWORKS",
    "REBEL SPORT",
    "ANACONDA",
    "BCF",
    "BOWRAL",
    "AUTOBARN",
    "AMART",
    "KITCHENWARE KINGDOM",
    "BED BATH N TABLE",
    "PILLOW TALK",
    "LINCRAFT",
    "LOWES",
    "EBAY",
    "AMAZON AU",
    "NANDOS",
    "DOMINOS",
    "PIZZA HUT",
    "GUZMAN Y GOMEZ",
    "GYG",
    "OPORTO",
    "GRILLD",
    "ZAMBARO",
    "BOOST JUICE",
    "JAMBA JUICE",
    "RED ROOSTER",
    "BAKERS DELIGHT",
    "BRUMBIES",
    "CHATIME",
    "DEGANI",
    "CRAZY CLARK",
    "RED DOT",
    "HOT DOLLAR",
    "DOLLAR KING",
    "GO LO",
    "EATALY",
    "SUBSY",
    "HARRYS CAFE DE WHEELS",
    "GELATO",
    "MADMEX",
    "MARRYBROWN",
    "SIMONS RICE",
    "LA MESA",
    "GYOZA DOBU",
    "SAKA",
    "HOYTS",
    "EVENT CINEMAS",
    "VILLAGE CINEMAS",
    "TICKETEK",
    "TICKETMASTER",
    "PAYPAL",
    "AFTERPAY",
    "ZIP PAY",
    "KLARNA",
    "HUMM",
    "BPAY",
    "SQUARE AU",
  ].map((pattern) => ({ pattern, categoryKey: "shoppingDining", confidence: IMPORT_CONFIDENCE.HIGH })),
  ...["CHEMIST WAREHOUSE", "PHARMACY", "PRICELINE", "AMCAL", "TERRYWHITE CHEMMART", "DENTAL", "MEDICAL", "MEDICAL CENTRE", "MEDICAL PRACTICE", "DR WING", "EDWARD WONG", "SPECSAVERS", "OSCAR WYLEE", "BAILEY NELSON", "PHYSIOTHERAPY", "CHIROPRACTIC", "DENTIST", "SULLIVAN NICOLAIDES", "DOUGLAS HANLY MOIR", "IMED", "CAPITAL RADIOLOGY", "MEDICARE"].map((pattern) => ({
    pattern,
    categoryKey: "medical",
    confidence: IMPORT_CONFIDENCE.HIGH,
  })),
  ...["BUPA", "MEDIBANK", "NIB", "HCF", "HBF", "GMHBA", "AUSTRALIAN UNITY", "DEFENCE HEALTH", "POLICE HEALTH", "TEACHERS HEALTH", "CBHS", "HIF", "WESTFUND", "AHM", "FRANK HEALTH"].map((pattern) => ({
      pattern,
      categoryKey: "privateInsurance",
      confidence: IMPORT_CONFIDENCE.HIGH,
    })),
  ...["AAMI", "BUDGET DIRECT", "NRMA", "RACV", "RACQ", "RAC INSURANCE", "RAA", "SUNCORP", "GIO", "ALLIANZ", "QBE", "COMMINSURE", "YOUI", "COLES INSURANCE", "WOOLWORTHS INSURANCE", "APIA", "VIRGIN MONEY INSURANCE", "REAL INSURANCE", "COVER-MORE", "TIO", "ZURICH", "CHUBB", "RACT", "IAG"].map((pattern) => ({
    pattern,
    categoryKey: "carInsurance",
    confidence: IMPORT_CONFIDENCE.HIGH,
  })),
  ...["HOLLARD", "CBA INSURANCE", "ALLIANZ", "SUNCORP", "CGU", "NRMA", "RACV", "BUDGET DIRECT", "YOU INSURANCE"].map((pattern) => ({
      pattern,
      categoryKey: "homeInsurance",
      confidence: IMPORT_CONFIDENCE.HIGH,
    })),
  ...["LUMO ENERGY", "ORIGIN ENERGY", "ENERGYAUSTRALIA", "RED ENERGY", "ALINTA", "SIMPLY ENERGY", "DODO POWER", "MOMENTUM ENERGY", "POWERSHOP", "SUMO POWER", "COVAU", "AMBER ELECTRIC", "TANGO ENERGY", "DISCOVER ENERGY", "GLOBIRD", "1ST ENERGY"].map((pattern) => ({
    pattern,
    categoryKey: "electricity",
    confidence: IMPORT_CONFIDENCE.HIGH,
  })),
  ...["AGL SALES", "ORIGIN ENERGY", "ENERGYAUSTRALIA"].map((pattern) => ({
    pattern,
    categoryKey: "gas",
    confidence: IMPORT_CONFIDENCE.HIGH,
  })),
  ...["YARRA VALLEY WATER", "SYDNEY WATER", "MELBOURNE WATER", "SOUTH EAST WATER", "SA WATER", "WATER CORPORATION", "ICON WATER", "HUNTER WATER", "GOLD COAST WATER", "URBAN UTILITIES", "BARWON WATER", "CITY WEST WATER", "TASWATER"].map((pattern) => ({
    pattern,
    categoryKey: "water",
    confidence: IMPORT_CONFIDENCE.HIGH,
  })),
  ...["TPG", "MORE TELECOM", "IINET", "TELSTRA", "OPTUS", "VODAFONE", "NETFLIX", "SPOTIFY", "APPLE", "GOOGLE", "MICROSOFT", "OPENAI", "GODADDY", "MATHSPACE", "AUSSIE BROADBAND", "SUPERLOOP", "LAUNTEL", "SPINTEL", "MATE COMMUNICATE", "FELIX MOBILE", "LEBARA", "ALDI MOBILE", "CATCH CONNECT", "KOALA MOBILE", "MOOSE MOBILE", "PENNYTEL", "BELONG", "PRIMUS", "SOUTHERN CROSS TELCO", "EXETEL", "BOOST MOBILE", "MYREPUBLIC", "VIRGIN MOBILE", "STAN", "BINGE", "KAYO", "DISNEY+", "DISNEY PLUS", "PARAMOUNT+", "AMAZON PRIME", "APPLE TV", "YOUTUBE PREMIUM", "XBOX", "PLAYSTATION", "NINTENDO"].map((pattern) => ({
      pattern,
      categoryKey: "internetMobile",
      confidence: IMPORT_CONFIDENCE.HIGH,
    })),
  ...["BP", "EG GROUP", "DGB PETRO", "SHELL", "CALTEX", "AMPOL", "EASTLINK", "MYKI", "PUBLIC TRANSPORT", "POINT PARKING", "DEPARTMENT OF TRANSPOR", "VOLVOCARS", "7-ELEVEN", "UNITED PETROLEUM", "LIBERTY OIL", "FREEDOM FUELS", "GULL", "PUMA ENERGY", "REDDY EXPRESS", "SOLO OIL", "EXXONMOBIL", "GOLDEN FLEECE", "NEPTUNE OIL", "METRO PETROLEUM", "SPEEDWAY", "COLES EXPRESS", "VIVA ENERGY", "UBER", "DIDI", "CHARGE FOX", "CHARGE FOX"].map((pattern) => ({
      pattern,
      categoryKey: "transport",
      confidence: IMPORT_CONFIDENCE.HIGH,
    })),
  ...["SCHOOL FEE", "SCHOOL FEES", "UNIVERSITY", "TAFE", "TUITION", "TUTORING",
    "PSW"].map((pattern) => ({
    pattern,
    categoryKey: "school",
    confidence: IMPORT_CONFIDENCE.HIGH,
  })),
  ...["VICROADS", "MANNINGHAM CITY", "ATO", "AUSTRALIAN TAXATION", "SERVICES AUSTRALIA", "CENTRELINK", "SERVICE NSW", "SERVICE SA", "MAIN ROADS WA", "AUSTRALIA POST", "AUSPOST", "CHILD SUPPORT", "COUNCIL RATES", "REVENUE NSW", "STATE REVENUE", "RTA", "HOME AFFAIRS", "BORDER FORCE", "FAIR WORK"].map((pattern) => ({
      pattern,
      categoryKey: "government",
      confidence: IMPORT_CONFIDENCE.HIGH,
    })),
  ...["KOENIGMACHINERY", "SNAZZI ALTERATIONS", "YARRA BOTANICA", "PET STOCK", "PETCIRCLE", "ANIMATE", "RSPCA", "VET", "VETERINARY", "ANIMAL HOSPITAL", "ANIMAL MEDICAL"].map((pattern) => ({
      pattern,
      categoryKey: "incidentals",
      confidence: IMPORT_CONFIDENCE.LOW,
      requiresReview: true,
    })),
];
